"""Exploratory reconstruction of Stadlmann's bounded-gap optimization."""

from .coefficients import large_simplex_coefficients, small_cube_coefficients
from .integrals import (
    ExactSupportParameters,
    IntegralMatrices,
    exact_i_entry,
    exact_ijk_matrices,
    exact_j_entry,
    exact_k_entry,
    monomial,
)
from .distribution import (
    ANALYTIC_CONSTRAINTS,
    ANALYTIC_CONSTRAINT_IDS,
    AnalyticConstraint,
    AnalyticSlack,
    ConstraintFailure,
    DistributionCertificate,
    Minorant,
    RegionCell,
    cells_from_support,
    constraint_failures,
    is_certified,
    support_constraint_failures,
    support_constraint_slacks,
)
from .breakthrough import (
    BreakthroughDiagnostic,
    MinimumBreakthroughExperiment,
    minimum_breakthrough,
)
from .symmetric import (
    FactorialMomentTable,
    SparseCertificateEvaluation,
    SparseSymmetricTerm,
    SymmetricBasisTerm,
    SymmetricSimplexMatrices,
    assemble_symmetric_simplex_matrices,
    enlarged_simplex_pairing,
    evaluate_sparse_symmetric_certificate,
    factorial_moment,
    load_sparse_symmetric_terms,
    monomial_symmetric_polynomial,
    simplex_marginal_pairing,
)
from .shadow_prices import (
    CandidateDiagnostic,
    ConstraintRelaxation,
    ScoredSupport,
    ShadowPriceExperiment,
    rank_constraint_relaxations,
)
from .parity import (
    ParityContributions,
    RoughFactorConstants,
    degree_three_prime_indicator,
    liouville_third_moment_prime_indicator,
    parity_contributions,
    parity_error_budget,
    rough_factor_constants,
)

__all__ = [
    "ANALYTIC_CONSTRAINTS",
    "ANALYTIC_CONSTRAINT_IDS",
    "AnalyticConstraint",
    "AnalyticSlack",
    "BreakthroughDiagnostic",
    "ConstraintFailure",
    "CandidateDiagnostic",
    "ConstraintRelaxation",
    "DistributionCertificate",
    "Minorant",
    "ParityContributions",
    "MinimumBreakthroughExperiment",
    "RegionCell",
    "RoughFactorConstants",
    "ScoredSupport",
    "ShadowPriceExperiment",
    "cells_from_support",
    "constraint_failures",
    "is_certified",
    "ExactSupportParameters",
    "FactorialMomentTable",
    "IntegralMatrices",
    "SparseCertificateEvaluation",
    "SparseSymmetricTerm",
    "SymmetricBasisTerm",
    "SymmetricSimplexMatrices",
    "assemble_symmetric_simplex_matrices",
    "enlarged_simplex_pairing",
    "exact_i_entry",
    "exact_ijk_matrices",
    "exact_j_entry",
    "exact_k_entry",
    "degree_three_prime_indicator",
    "evaluate_sparse_symmetric_certificate",
    "factorial_moment",
    "large_simplex_coefficients",
    "load_sparse_symmetric_terms",
    "monomial",
    "monomial_symmetric_polynomial",
    "liouville_third_moment_prime_indicator",
    "minimum_breakthrough",
    "parity_contributions",
    "parity_error_budget",
    "rank_constraint_relaxations",
    "simplex_marginal_pairing",
    "small_cube_coefficients",
    "rough_factor_constants",
    "support_constraint_failures",
    "support_constraint_slacks",
]
