"""Exact symmetry-compressed simplex pairings and sparse certificates.

This module ports the reusable combinatorial layer of Axiom Math's
``PrimeGapsLib`` certificate: monomial-symmetric exponent signatures,
factorial moments, the nilpotent moment ladder, closed simplex/marginal
pairings, and degree-grouped sparse quadratic-form contraction.
"""

from __future__ import annotations

from collections import Counter, defaultdict
from collections.abc import Iterable, Iterator, Sequence
from dataclasses import dataclass
from fractions import Fraction
from functools import cache
from itertools import product
import json
from math import comb, factorial
from numbers import Integral
from pathlib import Path


Signature = tuple[int, ...]
Exponent = tuple[int, ...]


def canonical_signature(values: Iterable[int]) -> Signature:
    """Return a zero-free exponent signature in non-increasing order."""
    converted = tuple(int(value) for value in values)
    if any(value < 0 for value in converted):
        raise ValueError("signature parts must be non-negative")
    return tuple(sorted((value for value in converted if value), reverse=True))


def erase_signature_part(values: Iterable[int], part: int) -> Signature:
    """Erase one occurrence of ``part``; erasing zero is the identity."""
    signature = canonical_signature(values)
    if part == 0:
        return signature
    if part not in signature:
        raise ValueError(f"signature does not contain {part}")
    result = list(signature)
    result.remove(part)
    return tuple(result)


def erasure_closure(signatures: Iterable[Iterable[int]]) -> tuple[Signature, ...]:
    """Return the deterministic family generated by all one-part erasures."""
    closure = {canonical_signature(value) for value in signatures}
    pending = list(closure)
    while pending:
        current = pending.pop()
        for part in set(current):
            target = erase_signature_part(current, part)
            if target not in closure:
                closure.add(target)
                pending.append(target)
    return tuple(sorted(closure, key=lambda value: (len(value), sum(value), value)))


def _multiset_permutations(counts: Counter[int], length: int) -> Iterator[Exponent]:
    if length == 0:
        yield ()
        return
    for value in sorted(counts, reverse=True):
        if counts[value] == 0:
            continue
        counts[value] -= 1
        for tail in _multiset_permutations(counts, length - 1):
            yield (value,) + tail
        counts[value] += 1


def monomial_symmetric_exponents(values: Iterable[int], dimension: int) -> Iterator[Exponent]:
    """Yield each exponent vector in a monomial-symmetric orbit exactly once.

    This explicit expansion is an audit helper for small dimensions.  Scalable
    assembly should use factorial moments instead of materializing the orbit.
    """
    signature = canonical_signature(values)
    if dimension < 0 or len(signature) > dimension:
        raise ValueError("signature has more parts than the ambient dimension")
    padded = signature + (0,) * (dimension - len(signature))
    yield from _multiset_permutations(Counter(padded), dimension)


def monomial_symmetric_polynomial(
    values: Iterable[int], dimension: int, coefficient: int | Fraction = 1
) -> dict[Exponent, Fraction]:
    """Expand a monomial-symmetric polynomial for low-dimensional auditing."""
    factor = Fraction(coefficient)
    if factor == 0:
        return {}
    return {exponent: factor for exponent in monomial_symmetric_exponents(values, dimension)}


def _multinomial(counts: Sequence[int]) -> int:
    result = factorial(sum(counts))
    for count in counts:
        result //= factorial(count)
    return result


def _signature_groups(signature: Signature) -> tuple[tuple[int, int], ...]:
    counts = Counter(signature)
    return tuple(sorted(counts.items(), key=lambda item: (item[1], item[0])))


def _orientation_cost(groups: Sequence[tuple[int, int]], other: Sequence[tuple[int, int]]) -> int:
    branching = 1
    for _, count in other:
        branching *= count + 1
    return len(groups) * branching


def _factorial_moment_oriented(
    dimension: int,
    groups: tuple[tuple[int, int], ...],
    other: tuple[tuple[int, int], ...],
) -> int:
    values = tuple(value for value, _ in other)
    initial_counts = tuple(count for _, count in other)

    @cache
    def visit(k: int, group_index: int, counts: tuple[int, ...]) -> int:
        if group_index == len(groups):
            return (
                comb(k, sum(counts))
                * _multinomial(counts)
                * _product(factorial(value) ** count for value, count in zip(values, counts))
            )
        exponent, slots = groups[group_index]
        total = 0
        for used in product(*(range(count + 1) for count in counts)):
            overlap = sum(used)
            if overlap > slots:
                continue
            weight = (
                comb(slots, overlap)
                * _multinomial(used)
                * factorial(exponent) ** (slots - overlap)
                * _product(
                    factorial(exponent + value) ** count
                    for value, count in zip(values, used)
                )
            )
            remaining = tuple(count - count_used for count, count_used in zip(counts, used))
            total += weight * visit(k - slots, group_index + 1, remaining)
        return comb(k, slots) * total

    return visit(dimension, 0, initial_counts)


def factorial_moment(dimension: int, left: Iterable[int], right: Iterable[int]) -> int:
    """Evaluate a monomial-symmetric factorial moment by overlap profiles.

    The cheaper of the two signature orientations is chosen from its
    multiplicity-profile branching estimate.
    """
    alpha = canonical_signature(left)
    beta = canonical_signature(right)
    if dimension < 0 or max(len(alpha), len(beta)) > dimension:
        return 0
    left_groups = _signature_groups(alpha)
    right_groups = _signature_groups(beta)
    if _orientation_cost(left_groups, right_groups) <= _orientation_cost(
        right_groups, left_groups
    ):
        return _factorial_moment_oriented(dimension, left_groups, right_groups)
    return _factorial_moment_oriented(dimension, right_groups, left_groups)


def _triangular_index(left: int, right: int) -> int:
    if left > right:
        left, right = right, left
    return right * (right + 1) // 2 + left


class FactorialMomentTable:
    """Batch factorial moments from an erase-closed nilpotent ladder.

    Writing the coordinate-splitting transition as ``I + N`` makes ``N``
    nilpotent on a bounded signature family.  We compute its short ladder once
    and reconstruct any requested dimension with binomial coefficients.
    """

    def __init__(self, signatures: Iterable[Iterable[int]], dimensions: Iterable[int]):
        self.signatures = erasure_closure(signatures)
        self.dimensions = tuple(sorted(set(int(value) for value in dimensions)))
        if not self.dimensions or min(self.dimensions) < 0:
            raise ValueError("at least one non-negative dimension is required")
        self._index = {signature: index for index, signature in enumerate(self.signatures)}
        signature_count = len(self.signatures)
        pair_count = signature_count * (signature_count + 1) // 2

        erase_rows = tuple(
            tuple(
                (part, self._index[erase_signature_part(signature, part)])
                for part in sorted(set(signature))
            )
            for signature in self.signatures
        )
        pair_buckets: dict[int, list[tuple[int, int, int]]] = defaultdict(list)
        for right in range(signature_count):
            for left in range(right + 1):
                part_count = len(self.signatures[left]) + len(self.signatures[right])
                pair_buckets[part_count].append(
                    (left, right, _triangular_index(left, right))
                )

        empty = self._index[()]
        previous = [0] * pair_count
        previous[_triangular_index(empty, empty)] = 1
        tables = {dimension: previous.copy() for dimension in self.dimensions}
        max_level = max(pair_buckets, default=0)

        for level in range(1, max_level + 1):
            current = [0] * pair_count
            for part_count in range(level, min(2 * level, max_level) + 1):
                for left, right, pair_index in pair_buckets[part_count]:
                    total = 0
                    for y, erased_right in erase_rows[right]:
                        total += factorial(y) * previous[
                            _triangular_index(left, erased_right)
                        ]
                    for x, erased_left in erase_rows[left]:
                        total += factorial(x) * previous[
                            _triangular_index(erased_left, right)
                        ]
                        for y, erased_right in erase_rows[right]:
                            total += factorial(x + y) * previous[
                                _triangular_index(erased_left, erased_right)
                            ]
                    current[pair_index] = total

            for dimension, table in tables.items():
                multiplier = comb(dimension, level)
                if multiplier == 0:
                    continue
                for part_count in range(level, min(2 * level, max_level) + 1):
                    for _, _, pair_index in pair_buckets[part_count]:
                        value = current[pair_index]
                        if value:
                            table[pair_index] += multiplier * value
            previous = current
        self._tables = tables

    def get(self, dimension: int, left: Iterable[int], right: Iterable[int]) -> int:
        """Look up one moment, canonicalizing both signatures."""
        alpha = canonical_signature(left)
        beta = canonical_signature(right)
        if dimension not in self._tables:
            raise KeyError(f"dimension {dimension} was not requested")
        try:
            left_index = self._index[alpha]
            right_index = self._index[beta]
        except KeyError as exc:
            raise KeyError("signature is outside the table's erasure closure") from exc
        return self._tables[dimension][_triangular_index(left_index, right_index)]


def _product(values: Iterable[int]) -> int:
    result = 1
    for value in values:
        result *= value
    return result


def enlarged_simplex_pairing(
    dimension: int,
    radius: int | Fraction,
    left_slack: int,
    left_signature: Iterable[int],
    right_slack: int,
    right_signature: Iterable[int],
    *,
    moments: FactorialMomentTable | None = None,
) -> Fraction:
    """Pair ``(R-sum t)^a m_alpha`` and ``(R-sum t)^b m_beta`` exactly."""
    alpha = canonical_signature(left_signature)
    beta = canonical_signature(right_signature)
    if min(dimension, left_slack, right_slack) < 0 or max(len(alpha), len(beta)) > dimension:
        raise ValueError("invalid dimension, slack exponent, or signature")
    total_degree = left_slack + right_slack + sum(alpha) + sum(beta)
    moment = (
        moments.get(dimension, alpha, beta)
        if moments is not None
        else factorial_moment(dimension, alpha, beta)
    )
    return (
        Fraction(radius) ** (dimension + total_degree)
        * factorial(left_slack + right_slack)
        * moment
        / factorial(dimension + total_degree)
    )


def radial_integral_factor(
    q: int,
    outer_radius: int | Fraction,
    radial_degree: int,
    gap: int | Fraction,
) -> Fraction:
    """The radial factor after integrating a distinguished coordinate."""
    if q < 0 or radial_degree < 0:
        raise ValueError("radial exponents must be non-negative")
    radius = Fraction(outer_radius)
    offset = Fraction(gap)
    return radius**q * sum(
        Fraction(comb(radial_degree, m) * factorial(m), factorial(m + q))
        * offset ** (radial_degree - m)
        * radius**m
        for m in range(radial_degree + 1)
    )


def simplex_marginal_pairing(
    dimension: int,
    inner_radius: int | Fraction,
    outer_radius: int | Fraction,
    left_slack: int,
    left_signature: Iterable[int],
    right_slack: int,
    right_signature: Iterable[int],
    *,
    moments: FactorialMomentTable | None = None,
) -> Fraction:
    """Pair one-coordinate marginals over a concentric outer simplex.

    Each marginal integrates its distinguished coordinate to the inner radius;
    their product is then integrated over the ``dimension - 1`` simplex of
    radius ``outer_radius``.
    """
    alpha = canonical_signature(left_signature)
    beta = canonical_signature(right_signature)
    inner = Fraction(inner_radius)
    outer = Fraction(outer_radius)
    if dimension < 1 or not 0 <= outer <= inner:
        raise ValueError("require dimension >= 1 and 0 <= outer_radius <= inner_radius")
    if min(left_slack, right_slack) < 0 or max(len(alpha), len(beta)) > dimension:
        raise ValueError("invalid slack exponent or signature")
    answer = Fraction(0)
    for left_part in (0, *sorted(set(alpha))):
        erased_left = erase_signature_part(alpha, left_part)
        left_factor = Fraction(
            factorial(left_part) * factorial(left_slack),
            factorial(left_slack + left_part + 1),
        )
        for right_part in (0, *sorted(set(beta))):
            erased_right = erase_signature_part(beta, right_part)
            right_factor = Fraction(
                factorial(right_part) * factorial(right_slack),
                factorial(right_slack + right_part + 1),
            )
            q = dimension - 1 + sum(erased_left) + sum(erased_right)
            radial_degree = (
                left_slack + left_part + 1 + right_slack + right_part + 1
            )
            moment = (
                moments.get(dimension - 1, erased_left, erased_right)
                if moments is not None
                else factorial_moment(dimension - 1, erased_left, erased_right)
            )
            answer += (
                left_factor
                * right_factor
                * radial_integral_factor(q, outer, radial_degree, inner - outer)
                * moment
            )
    return answer


@dataclass(frozen=True)
class SymmetricBasisTerm:
    slack_power: int
    signature: Signature

    def __post_init__(self) -> None:
        if not isinstance(self.slack_power, Integral) or self.slack_power < 0:
            raise ValueError("slack_power must be a non-negative integer")
        object.__setattr__(self, "slack_power", int(self.slack_power))
        object.__setattr__(self, "signature", canonical_signature(self.signature))


@dataclass(frozen=True)
class SymmetricSimplexMatrices:
    mass: tuple[tuple[Fraction, ...], ...]
    marginal: tuple[tuple[Fraction, ...], ...]


def assemble_symmetric_simplex_matrices(
    basis: Sequence[SymmetricBasisTerm],
    dimension: int,
    inner_radius: int | Fraction,
    outer_radius: int | Fraction,
) -> SymmetricSimplexMatrices:
    """Assemble exact symmetric mass/marginal matrices with one shared moment table."""
    if not basis:
        raise ValueError("basis must be non-empty")
    moments = FactorialMomentTable(
        (term.signature for term in basis), (dimension - 1, dimension)
    )
    size = len(basis)
    mass = [[Fraction(0) for _ in range(size)] for _ in range(size)]
    marginal = [[Fraction(0) for _ in range(size)] for _ in range(size)]
    for row, left in enumerate(basis):
        for column in range(row, size):
            right = basis[column]
            mass_value = enlarged_simplex_pairing(
                dimension,
                inner_radius,
                left.slack_power,
                left.signature,
                right.slack_power,
                right.signature,
                moments=moments,
            )
            marginal_value = simplex_marginal_pairing(
                dimension,
                inner_radius,
                outer_radius,
                left.slack_power,
                left.signature,
                right.slack_power,
                right.signature,
                moments=moments,
            )
            mass[row][column] = mass[column][row] = mass_value
            marginal[row][column] = marginal[column][row] = marginal_value
    return SymmetricSimplexMatrices(
        tuple(tuple(row) for row in mass), tuple(tuple(row) for row in marginal)
    )


@dataclass(frozen=True)
class SparseSymmetricTerm:
    slack_power: int
    signature: Signature
    coefficient: int

    def __post_init__(self) -> None:
        if not isinstance(self.slack_power, Integral) or self.slack_power < 0:
            raise ValueError("slack_power must be a non-negative integer")
        if not isinstance(self.coefficient, Integral):
            raise TypeError("sparse certificate coefficients must be integers")
        object.__setattr__(self, "slack_power", int(self.slack_power))
        object.__setattr__(self, "signature", canonical_signature(self.signature))
        object.__setattr__(self, "coefficient", int(self.coefficient))


def load_sparse_symmetric_terms(path: str | Path) -> tuple[SparseSymmetricTerm, ...]:
    """Load PrimeGapsLib-style ``[slack, signature, coefficient]`` JSON."""
    payload = json.loads(Path(path).read_text())
    if not isinstance(payload, list):
        raise ValueError("sparse symmetric certificate must be a JSON array")
    combined: dict[tuple[int, Signature], int] = defaultdict(int)
    for entry in payload:
        if not isinstance(entry, list) or len(entry) != 3 or not isinstance(entry[1], list):
            raise ValueError("each certificate entry must be [slack, signature, coefficient]")
        term = SparseSymmetricTerm(entry[0], tuple(entry[1]), entry[2])
        combined[(term.slack_power, term.signature)] += term.coefficient
    return tuple(
        SparseSymmetricTerm(slack, signature, coefficient)
        for (slack, signature), coefficient in sorted(
            combined.items(), key=lambda item: (item[0][0], sum(item[0][1]), item[0][1])
        )
        if coefficient
    )


def _descending_factorial(n: int, count: int) -> int:
    if not 0 <= count <= n:
        raise ValueError(f"invalid descending factorial ({n}, {count})")
    return _product(range(n - count + 1, n + 1))


@cache
def _cleared_mass_scalar(
    dimension: int,
    epsilon_denominator: int,
    degree_bound: int,
    degree: int,
    slack_sum: int,
) -> int:
    return (
        (epsilon_denominator + 1) ** (dimension + degree)
        * epsilon_denominator ** (dimension + 1 - degree)
        * factorial(slack_sum)
        * _descending_factorial(2 * dimension + 1, dimension + 1 - degree)
        * factorial(degree_bound + 1) ** 2
    )


@cache
def _cleared_marginal_factor(degree_bound: int, slack: int, exponent: int) -> int:
    return (
        factorial(exponent)
        * factorial(slack)
        * _descending_factorial(degree_bound + 1, degree_bound - (slack + exponent))
    )


@cache
def _cleared_radial_factor(
    dimension: int, epsilon_denominator: int, q: int, radial_degree: int
) -> int:
    inner = sum(
        comb(radial_degree, m)
        * 2 ** (radial_degree - m)
        * (epsilon_denominator - 1) ** m
        * factorial(m)
        * _descending_factorial(2 * dimension + 1, 2 * dimension + 1 - (m + q))
        for m in range(radial_degree + 1)
    )
    return (
        epsilon_denominator ** (2 * dimension + 1 - (q + radial_degree))
        * (epsilon_denominator - 1) ** q
        * inner
    )


@dataclass(frozen=True)
class SparseCertificateEvaluation:
    dimension: int
    epsilon_denominator: int
    degree_bound: int
    term_count: int
    signature_count: int
    mass_group_count: int
    mass_transform_count: int
    marginal_feature_count: int
    marginal_group_count: int
    marginal_transform_count: int
    mass: int
    marginal: int

    @property
    def difference(self) -> int:
        return self.dimension * self.marginal - 4 * self.mass

    @property
    def quotient(self) -> Fraction:
        return Fraction(self.dimension * self.marginal, self.mass)

    @property
    def certified(self) -> bool:
        return self.mass > 0 and self.difference > 0


@dataclass(frozen=True)
class _MarginalFeature:
    signature: Signature
    weight: int


def evaluate_sparse_symmetric_certificate(
    terms: Sequence[SparseSymmetricTerm],
    dimension: int,
    epsilon_denominator: int,
    *,
    degree_bound: int | None = None,
) -> SparseCertificateEvaluation:
    """Evaluate a sparse ``M_{k,epsilon} > 4`` certificate with integer arithmetic.

    Denominators are cleared globally.  Terms are grouped by degree, repeated
    signature-moment transforms are cached, only the smaller side of each
    group pair is contracted, and symmetry reduces the square to its upper
    triangle.
    """
    if not terms:
        raise ValueError("certificate must contain at least one nonzero term")
    if dimension < 1 or epsilon_denominator < 1:
        raise ValueError("dimension and epsilon denominator must be positive")
    if any(term.coefficient == 0 for term in terms):
        raise ValueError("zero terms must be removed from sparse certificates")
    inferred_bound = max(term.slack_power + sum(term.signature) for term in terms)
    degree_bound = inferred_bound if degree_bound is None else int(degree_bound)
    if degree_bound < inferred_bound:
        raise ValueError("degree bound is smaller than a certificate term")
    if 2 * degree_bound > dimension:
        raise ValueError("cleared formula requires 2 * degree_bound <= dimension")

    moments = FactorialMomentTable(
        (term.signature for term in terms), (dimension - 1, dimension)
    )
    mass_group_map: dict[tuple[int, int], list[SparseSymmetricTerm]] = defaultdict(list)
    for term in terms:
        mass_group_map[(term.slack_power, sum(term.signature))].append(term)
    mass_groups = tuple(
        (key, tuple(group)) for key, group in sorted(mass_group_map.items())
    )
    mass_transforms: dict[tuple[int, Signature], int] = {}

    def mass_transform(group_index: int, target: Signature) -> int:
        key = group_index, target
        if key not in mass_transforms:
            mass_transforms[key] = sum(
                term.coefficient * moments.get(dimension, target, term.signature)
                for term in mass_groups[group_index][1]
            )
        return mass_transforms[key]

    mass = 0
    for left_index, ((left_slack, left_degree), left_group) in enumerate(mass_groups):
        for right_index in range(left_index, len(mass_groups)):
            (right_slack, right_degree), right_group = mass_groups[right_index]
            if len(left_group) <= len(right_group):
                source, destination = left_group, right_index
            else:
                source, destination = right_group, left_index
            contraction = sum(
                term.coefficient * mass_transform(destination, term.signature)
                for term in source
            )
            slack_sum = left_slack + right_slack
            total_degree = slack_sum + left_degree + right_degree
            mass += (1 if left_index == right_index else 2) * contraction * (
                _cleared_mass_scalar(
                    dimension,
                    epsilon_denominator,
                    degree_bound,
                    total_degree,
                    slack_sum,
                )
            )

    feature_weights: dict[tuple[int, int, Signature], int] = defaultdict(int)
    for term in terms:
        for exponent in (0, *sorted(set(term.signature))):
            erased = erase_signature_part(term.signature, exponent)
            key = (
                sum(term.signature) - exponent,
                term.slack_power + exponent + 1,
                erased,
            )
            feature_weights[key] += term.coefficient * _cleared_marginal_factor(
                degree_bound, term.slack_power, exponent
            )
    marginal_group_map: dict[tuple[int, int], list[_MarginalFeature]] = defaultdict(list)
    for (residual, radial, signature), weight in feature_weights.items():
        if weight:
            marginal_group_map[(residual, radial)].append(
                _MarginalFeature(signature, weight)
            )
    marginal_groups = tuple(
        (key, tuple(group)) for key, group in sorted(marginal_group_map.items())
    )
    marginal_transforms: dict[tuple[int, Signature], int] = {}

    def marginal_transform(group_index: int, target: Signature) -> int:
        key = group_index, target
        if key not in marginal_transforms:
            marginal_transforms[key] = sum(
                feature.weight * moments.get(dimension - 1, target, feature.signature)
                for feature in marginal_groups[group_index][1]
            )
        return marginal_transforms[key]

    marginal = 0
    for left_index, ((left_residual, left_radial), left_group) in enumerate(
        marginal_groups
    ):
        for right_index in range(left_index, len(marginal_groups)):
            (right_residual, right_radial), right_group = marginal_groups[right_index]
            if len(left_group) <= len(right_group):
                source, destination = left_group, right_index
            else:
                source, destination = right_group, left_index
            contraction = sum(
                feature.weight * marginal_transform(destination, feature.signature)
                for feature in source
            )
            q = dimension - 1 + left_residual + right_residual
            radial_degree = left_radial + right_radial
            marginal += (1 if left_index == right_index else 2) * contraction * (
                _cleared_radial_factor(
                    dimension, epsilon_denominator, q, radial_degree
                )
            )

    return SparseCertificateEvaluation(
        dimension=dimension,
        epsilon_denominator=epsilon_denominator,
        degree_bound=degree_bound,
        term_count=len(terms),
        signature_count=len(moments.signatures),
        mass_group_count=len(mass_groups),
        mass_transform_count=len(mass_transforms),
        marginal_feature_count=sum(len(group) for _, group in marginal_groups),
        marginal_group_count=len(marginal_groups),
        marginal_transform_count=len(marginal_transforms),
        mass=mass,
        marginal=marginal,
    )
